/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AppArgs {
  payloadHandler: (...args: any[]) => any
}
export class App {
  constructor(args: AppArgs)
  start(waitMs: number): Promise<void>
}
